import {
  Tender,
  VendorBid,
  Clarification,
  Evaluation,
  NoticeToAward,
  Dispute,
  Milestone,
  EscrowEvent,
  Notification,
  User,
} from "./types"
import { addBusinessDays } from "./businessDays"

const now = new Date()

// Mock Tenders
export const mockTenders: Tender[] = [
  {
    id: "tender-1",
    entityId: "entity-1",
    title: "Road Construction Project - A1 Highway Extension",
    description: "Construction of 25km highway extension including bridges and drainage systems",
    category: "Infrastructure",
    budget: 45000000,
    currency: "BWP",
    stage: "submission",
    publishedAt: addBusinessDays(now, -15),
    clarificationDeadline: addBusinessDays(now, -5),
    submissionDeadline: addBusinessDays(now, 3),
    evaluationDeadline: addBusinessDays(now, 10),
    documentUrls: ["/documents/tender-1-spec.pdf", "/documents/tender-1-drawings.pdf"],
    requirements: [
      "Minimum 10 years experience in highway construction",
      "Grade A contractor registration",
      "ISO 9001 certification",
      "Equipment capacity for large-scale projects",
    ],
    isSealed: true,
    allowClarifications: true,
    allowResubmissions: false,
    createdAt: addBusinessDays(now, -20),
    updatedAt: now,
  },
  {
    id: "tender-2",
    entityId: "entity-1",
    title: "School Building Construction - 5 Primary Schools",
    description: "Construction of 5 modern primary schools across rural districts",
    category: "Education Infrastructure",
    budget: 28000000,
    currency: "BWP",
    stage: "evaluation",
    publishedAt: addBusinessDays(now, -30),
    clarificationDeadline: addBusinessDays(now, -20),
    submissionDeadline: addBusinessDays(now, -10),
    evaluationDeadline: addBusinessDays(now, 2),
    documentUrls: ["/documents/tender-2-spec.pdf"],
    requirements: [
      "Experience in educational facility construction",
      "Grade B or higher contractor registration",
      "Health and safety certification",
    ],
    isSealed: true,
    allowClarifications: false,
    allowResubmissions: false,
    createdAt: addBusinessDays(now, -35),
    updatedAt: now,
  },
  {
    id: "tender-3",
    entityId: "entity-1",
    title: "IT Infrastructure Upgrade - Government Data Center",
    description: "Comprehensive upgrade of government data center infrastructure",
    category: "Technology",
    budget: 12500000,
    currency: "BWP",
    stage: "published",
    publishedAt: addBusinessDays(now, -2),
    clarificationDeadline: addBusinessDays(now, 8),
    submissionDeadline: addBusinessDays(now, 15),
    evaluationDeadline: addBusinessDays(now, 22),
    documentUrls: ["/documents/tender-3-spec.pdf"],
    requirements: [
      "Cisco certified infrastructure partner",
      "Minimum 5 years data center experience",
      "ISO 27001 certification",
    ],
    isSealed: true,
    allowClarifications: true,
    allowResubmissions: true,
    createdAt: addBusinessDays(now, -3),
    updatedAt: now,
  },
]

// Mock Vendor Bids
export const mockBids: VendorBid[] = [
  {
    id: "bid-1",
    tenderId: "tender-1",
    providerId: "provider-1",
    providerName: "BuildCorp Services Ltd",
    technicalProposalUrl: "/submissions/bid-1-technical.pdf",
    financialProposalUrl: "/submissions/bid-1-financial.pdf",
    technicalProposalHash: "a3b2c1d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890",
    financialProposalHash: "f1e2d3c4b5a67890fedcba0987654321fedcba0987654321fedcba0987654321",
    submittedAt: addBusinessDays(now, -8),
    isWithdrawn: false,
    version: 1,
    technicalScore: 85,
    financialScore: 92,
    totalScore: 88.5,
    isPreferred: true,
    createdAt: addBusinessDays(now, -8),
    updatedAt: now,
  },
  {
    id: "bid-2",
    tenderId: "tender-1",
    providerId: "provider-2",
    providerName: "Elite Construction Co.",
    technicalProposalUrl: "/submissions/bid-2-technical.pdf",
    financialProposalUrl: "/submissions/bid-2-financial.pdf",
    technicalProposalHash: "b4c3d2e1f0a98765dcbafe9876543210dcbafe9876543210dcbafe9876543210",
    financialProposalHash: "e0f1d2c3b4a56789efcdab0123456789efcdab0123456789efcdab0123456789",
    submittedAt: addBusinessDays(now, -7),
    isWithdrawn: false,
    version: 1,
    technicalScore: 78,
    financialScore: 85,
    totalScore: 81.5,
    isPreferred: false,
    createdAt: addBusinessDays(now, -7),
    updatedAt: now,
  },
  {
    id: "bid-3",
    tenderId: "tender-2",
    providerId: "provider-1",
    providerName: "BuildCorp Services Ltd",
    technicalProposalUrl: "/submissions/bid-3-technical.pdf",
    financialProposalUrl: "/submissions/bid-3-financial.pdf",
    technicalProposalHash: "c5d4e3f2a1b09876edcbaf0123456789edcbaf0123456789edcbaf0123456789",
    financialProposalHash: "d1e2f3a4b5c67890fedbca9876543210fedbca9876543210fedbca9876543210",
    submittedAt: addBusinessDays(now, -12),
    isWithdrawn: false,
    version: 1,
    technicalScore: 88,
    financialScore: 90,
    totalScore: 89,
    isPreferred: true,
    createdAt: addBusinessDays(now, -12),
    updatedAt: now,
  },
]

// Mock Clarifications
export const mockClarifications: Clarification[] = [
  {
    id: "clarif-1",
    tenderId: "tender-1",
    providerId: "provider-1",
    providerName: "BuildCorp Services Ltd",
    question: "Could you please clarify the soil testing requirements for the highway foundation?",
    answer:
      "Soil testing should be conducted every 500m along the route. Reports must be submitted within 14 days of testing.",
    isPublic: true,
    askedAt: addBusinessDays(now, -10),
    answeredAt: addBusinessDays(now, -8),
    createdAt: addBusinessDays(now, -10),
    updatedAt: addBusinessDays(now, -8),
  },
  {
    id: "clarif-2",
    tenderId: "tender-1",
    providerId: "provider-2",
    providerName: "Elite Construction Co.",
    question: "What is the expected timeline for material procurement approval?",
    answer:
      "Material procurement lists must be submitted 30 days before construction phase. Approval typically takes 10 business days.",
    isPublic: true,
    askedAt: addBusinessDays(now, -9),
    answeredAt: addBusinessDays(now, -7),
    createdAt: addBusinessDays(now, -9),
    updatedAt: addBusinessDays(now, -7),
  },
  {
    id: "clarif-3",
    tenderId: "tender-3",
    providerId: "provider-3",
    providerName: "TechSolutions Ltd",
    question: "Are there any specific requirements for data migration from legacy systems?",
    isPublic: true,
    askedAt: addBusinessDays(now, -1),
    createdAt: addBusinessDays(now, -1),
    updatedAt: addBusinessDays(now, -1),
  },
]

// Mock Disputes
export const mockDisputes: Dispute[] = [
  {
    id: "dispute-1",
    tenderId: "tender-2",
    providerId: "provider-2",
    providerName: "Elite Construction Co.",
    reason: "Evaluation Score Discrepancy",
    details:
      "We believe our technical proposal was not evaluated correctly according to the published criteria. Our experience and certifications meet all requirements but received lower than expected scores.",
    evidenceUrls: ["/disputes/dispute-1-evidence.pdf"],
    status: "under_review",
    reviewedBy: "admin-1",
    filedAt: addBusinessDays(now, -3),
    createdAt: addBusinessDays(now, -3),
    updatedAt: addBusinessDays(now, -1),
  },
  {
    id: "dispute-2",
    tenderId: "tender-1",
    providerId: "provider-1",
    providerName: "TechFlow Solutions",
    reason: "Unfair Disqualification",
    details:
      "Our bid was disqualified for allegedly not meeting technical requirements, but we have documentation proving compliance with all specifications.",
    evidenceUrls: ["/disputes/dispute-2-evidence.pdf", "/disputes/dispute-2-compliance.pdf"],
    status: "pending",
    filedAt: addBusinessDays(now, -1),
    createdAt: addBusinessDays(now, -1),
    updatedAt: addBusinessDays(now, -1),
  },
  {
    id: "dispute-3",
    tenderId: "tender-3",
    providerId: "provider-3",
    providerName: "Global Services Ltd.",
    reason: "Procurement Process Violation",
    details:
      "The tender evaluation process was not conducted according to the published timeline. Additional requirements were introduced after submission deadline.",
    evidenceUrls: ["/disputes/dispute-3-timeline.pdf"],
    status: "resolved",
    resolution: "Dispute upheld. Tender will be re-evaluated according to original criteria.",
    reviewedBy: "admin-1",
    resolvedAt: addBusinessDays(now, -2),
    filedAt: addBusinessDays(now, -7),
    createdAt: addBusinessDays(now, -7),
    updatedAt: addBusinessDays(now, -2),
  },
  {
    id: "dispute-4",
    tenderId: "tender-4",
    providerId: "provider-4",
    providerName: "Innovation Partners",
    reason: "Conflict of Interest",
    details:
      "We suspect one of the evaluators has a conflict of interest with the winning bidder. This may have affected the evaluation outcome.",
    evidenceUrls: ["/disputes/dispute-4-evidence.pdf"],
    status: "pending",
    filedAt: addBusinessDays(now, -2),
    createdAt: addBusinessDays(now, -2),
    updatedAt: addBusinessDays(now, -2),
  },
]

// Mock Evaluations
export const mockEvaluations: Evaluation[] = [
  {
    id: "eval-1",
    tenderId: "tender-2",
    bidId: "bid-3",
    evaluatorId: "entity-1",
    evaluatorName: "Ministry of Infrastructure",
    technicalScore: 88,
    technicalMaxScore: 100,
    financialScore: 90,
    financialMaxScore: 100,
    criteria: [
      { name: "Experience", score: 18, maxScore: 20, comments: "Excellent track record" },
      { name: "Methodology", score: 28, maxScore: 30, comments: "Well-structured approach" },
      { name: "Team Qualifications", score: 22, maxScore: 25, comments: "Strong team" },
      { name: "Equipment", score: 20, maxScore: 25, comments: "Adequate resources" },
    ],
    overallComments: "Strong proposal with comprehensive approach and experienced team.",
    recommendation: "award",
    evaluatedAt: addBusinessDays(now, -5),
    createdAt: addBusinessDays(now, -5),
    updatedAt: addBusinessDays(now, -5),
  },
]

// Mock Notices to Award
export const mockAwards: NoticeToAward[] = [
  {
    id: "award-1",
    tenderId: "tender-2",
    bidId: "bid-3",
    providerId: "provider-1",
    awardAmount: 27500000,
    awardDate: addBusinessDays(now, -2),
    contractStartDate: addBusinessDays(now, 14),
    contractEndDate: addBusinessDays(now, 180),
    termsUrl: "/contracts/award-1-terms.pdf",
    specialConditions: [
      "Weekly progress reports required",
      "Quality inspections every two weeks",
      "Penalty clause for delays beyond 7 days",
    ],
    isAccepted: true,
    acceptedAt: addBusinessDays(now, -1),
    createdAt: addBusinessDays(now, -2),
    updatedAt: addBusinessDays(now, -1),
  },
]

// Mock Milestones
export const mockMilestones: Milestone[] = [
  {
    id: "milestone-1",
    tenderId: "tender-2",
    noticeToAwardId: "award-1",
    title: "Site Preparation and Foundation",
    description: "Complete site clearing, leveling, and foundation work for all 5 schools",
    amount: 5500000,
    sequence: 1,
    dueDate: addBusinessDays(now, 30),
    status: "in_progress",
    deliverableUrls: [],
    createdAt: addBusinessDays(now, -1),
    updatedAt: now,
  },
  {
    id: "milestone-2",
    tenderId: "tender-2",
    noticeToAwardId: "award-1",
    title: "Structural Framework",
    description: "Complete structural framework and roofing for all buildings",
    amount: 11000000,
    sequence: 2,
    dueDate: addBusinessDays(now, 90),
    status: "pending",
    deliverableUrls: [],
    createdAt: addBusinessDays(now, -1),
    updatedAt: now,
  },
  {
    id: "milestone-3",
    tenderId: "tender-2",
    noticeToAwardId: "award-1",
    title: "Interior Works and Finishing",
    description: "Complete all interior works, finishing, and installations",
    amount: 8250000,
    sequence: 3,
    dueDate: addBusinessDays(now, 150),
    status: "pending",
    deliverableUrls: [],
    createdAt: addBusinessDays(now, -1),
    updatedAt: now,
  },
  {
    id: "milestone-4",
    tenderId: "tender-2",
    noticeToAwardId: "award-1",
    title: "Final Inspection and Handover",
    description: "Final inspections, corrections, and official handover",
    amount: 2750000,
    sequence: 4,
    dueDate: addBusinessDays(now, 180),
    status: "pending",
    deliverableUrls: [],
    createdAt: addBusinessDays(now, -1),
    updatedAt: now,
  },
]

// Mock Escrow Events
export const mockEscrowEvents: EscrowEvent[] = [
  {
    id: "escrow-1",
    tenderId: "tender-2",
    type: "deposit",
    amount: 27500000,
    balance: 27500000,
    description: "Initial project funds deposited to escrow",
    performedBy: "entity-1",
    performedByRole: "entity",
    timestamp: addBusinessDays(now, -1),
    createdAt: addBusinessDays(now, -1),
  },
  {
    id: "escrow-2",
    tenderId: "tender-2",
    milestoneId: "milestone-1",
    type: "hold",
    amount: 5500000,
    balance: 27500000,
    description: "Funds held for Milestone 1: Site Preparation and Foundation",
    performedBy: "admin-1",
    performedByRole: "admin",
    timestamp: addBusinessDays(now, -1),
    createdAt: addBusinessDays(now, -1),
  },
  // Provider's awarded tenders escrow events
  {
    id: "escrow-3",
    tenderId: "TND-004",
    type: "deposit",
    amount: 8200000,
    balance: 8200000,
    description: "Water Supply System Upgrade - Initial deposit",
    performedBy: "entity-1",
    performedByRole: "entity",
    timestamp: addBusinessDays(now, -15),
    createdAt: addBusinessDays(now, -15),
  },
  {
    id: "escrow-4",
    tenderId: "TND-004",
    type: "release",
    amount: 2460000,
    balance: 5740000,
    description: "Milestone 1 payment - System design approval",
    performedBy: "PROV-123",
    performedByRole: "provider",
    timestamp: addBusinessDays(now, -10),
    createdAt: addBusinessDays(now, -10),
  },
  {
    id: "escrow-5",
    tenderId: "TND-005",
    type: "deposit",
    amount: 12000000,
    balance: 12000000,
    description: "Solar Power Installation - Project funds deposited",
    performedBy: "entity-1",
    performedByRole: "entity",
    timestamp: addBusinessDays(now, -20),
    createdAt: addBusinessDays(now, -20),
  },
  {
    id: "escrow-6",
    tenderId: "TND-005",
    milestoneId: "milestone-solar-1",
    type: "hold",
    amount: 3600000,
    balance: 12000000,
    description: "Phase 1: Site preparation and equipment delivery",
    performedBy: "admin-1",
    performedByRole: "admin",
    timestamp: addBusinessDays(now, -18),
    createdAt: addBusinessDays(now, -18),
  },
  {
    id: "escrow-7",
    tenderId: "TND-005",
    type: "release",
    amount: 3600000,
    balance: 8400000,
    description: "Phase 1 completion payment",
    performedBy: "PROV-123",
    performedByRole: "provider",
    timestamp: addBusinessDays(now, -12),
    createdAt: addBusinessDays(now, -12),
  },
  {
    id: "escrow-8",
    tenderId: "TND-005",
    milestoneId: "milestone-solar-2",
    type: "hold",
    amount: 4800000,
    balance: 8400000,
    description: "Phase 2: Equipment installation (current)",
    performedBy: "admin-1",
    performedByRole: "admin",
    timestamp: addBusinessDays(now, -5),
    createdAt: addBusinessDays(now, -5),
  },
  {
    id: "escrow-9",
    tenderId: "TND-006",
    type: "deposit",
    amount: 3500000,
    balance: 3500000,
    description: "IT Infrastructure Modernization - Final project",
    performedBy: "entity-1",
    performedByRole: "entity",
    timestamp: addBusinessDays(now, -90),
    createdAt: addBusinessDays(now, -90),
  },
  {
    id: "escrow-10",
    tenderId: "TND-006",
    type: "release",
    amount: 3500000,
    balance: 0,
    description: "Final payment - Project completion",
    performedBy: "PROV-123",
    performedByRole: "provider",
    timestamp: addBusinessDays(now, -30),
    createdAt: addBusinessDays(now, -30),
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "entity-1",
    type: "submission_received",
    title: "New Bid Submitted",
    message: "BuildCorp Services Ltd submitted a bid for Road Construction Project",
    relatedId: "tender-1",
    relatedType: "bid",
    isRead: false,
    createdAt: addBusinessDays(now, -8),
  },
  {
    id: "notif-2",
    userId: "provider-1",
    type: "clarification_answered",
    title: "Clarification Answered",
    message: "Your clarification question for Road Construction Project has been answered",
    relatedId: "clarif-1",
    relatedType: "clarification",
    isRead: false,
    createdAt: addBusinessDays(now, -8),
  },
  {
    id: "notif-3",
    userId: "provider-1",
    type: "award_issued",
    title: "Contract Award",
    message: "Congratulations! You have been awarded the School Building Construction project",
    relatedId: "award-1",
    relatedType: "tender",
    isRead: false,
    createdAt: addBusinessDays(now, -2),
  },
  // Provider-specific notifications for PROV-123
  {
    id: "notif-4",
    userId: "PROV-123",
    type: "award_issued",
    title: "Contract Awarded - Water Supply System",
    message: "Congratulations! You have been awarded the Water Supply System Upgrade project worth P 8,200,000",
    relatedId: "TND-004",
    relatedType: "tender",
    isRead: false,
    createdAt: addBusinessDays(now, -15),
  },
  {
    id: "notif-5",
    userId: "PROV-123",
    type: "milestone_payment",
    title: "Milestone Payment Released",
    message: "Payment of P 3,600,000 has been released for Phase 1 completion of Solar Power Installation",
    relatedId: "TND-005",
    relatedType: "milestone",
    isRead: false,
    createdAt: addBusinessDays(now, -12),
  },
  {
    id: "notif-6",
    userId: "PROV-123",
    type: "clarification_answered",
    title: "Clarification Answered",
    message: "Your clarification question for National Road Infrastructure Upgrade has been answered",
    relatedId: "TND-001",
    relatedType: "clarification",
    isRead: true,
    createdAt: addBusinessDays(now, -5),
  },
  {
    id: "notif-7",
    userId: "PROV-123",
    type: "tender_published",
    title: "New Tender Available",
    message: "Hospital Equipment Procurement tender is now open for bidding. Closing date: 20 Feb 2025",
    relatedId: "TND-002",
    relatedType: "tender",
    isRead: false,
    createdAt: addBusinessDays(now, -3),
  },
  {
    id: "notif-8",
    userId: "PROV-123",
    type: "dispute_update",
    title: "Dispute Status Update",
    message: "Your dispute for School Building Construction (CASE-2025-001) is now under review",
    relatedId: "DIS-001",
    relatedType: "dispute",
    isRead: false,
    createdAt: addBusinessDays(now, -1),
  },
]

// Mock Users
export const mockUsers: User[] = [
  {
    id: "entity-1",
    email: "procurement@ministry.gov",
    name: "Ministry of Infrastructure",
    role: "entity",
    organizationName: "Ministry of Infrastructure",
    phone: "+1-555-0101",
    address: "123 Government Ave, Capital City",
    createdAt: addBusinessDays(now, -365),
    updatedAt: addBusinessDays(now, -30),
  },
  {
    id: "entity-2", 
    email: "admin@health.gov",
    name: "Department of Health",
    role: "entity",
    organizationName: "Department of Health",
    phone: "+1-555-0102",
    address: "456 Health Plaza, Capital City",
    createdAt: addBusinessDays(now, -300),
    updatedAt: addBusinessDays(now, -15),
  },
  {
    id: "provider-1",
    email: "contact@techflow.com",
    name: "TechFlow Solutions",
    role: "provider",
    organizationName: "TechFlow Solutions Inc.",
    phone: "+1-555-0201",
    address: "789 Tech Park, Innovation District",
    createdAt: addBusinessDays(now, -180),
    updatedAt: addBusinessDays(now, -5),
  },
  {
    id: "provider-2",
    email: "bids@eliteconstruction.com",
    name: "Elite Construction Co.",
    role: "provider",
    organizationName: "Elite Construction Co.",
    phone: "+1-555-0202",
    address: "321 Builder's Row, Industrial Zone",
    createdAt: addBusinessDays(now, -150),
    updatedAt: addBusinessDays(now, -10),
  },
  {
    id: "provider-3",
    email: "info@globalservices.com",
    name: "Global Services Ltd.",
    role: "provider",
    organizationName: "Global Services Ltd.",
    phone: "+1-555-0203",
    address: "654 Service Center, Business District",
    createdAt: addBusinessDays(now, -120),
    updatedAt: addBusinessDays(now, -7),
  },
  {
    id: "provider-4",
    email: "team@innovationpartners.com",
    name: "Innovation Partners",
    role: "provider",
    organizationName: "Innovation Partners LLC",
    phone: "+1-555-0204",
    address: "987 Innovation Blvd, Tech Quarter",
    createdAt: addBusinessDays(now, -90),
    updatedAt: addBusinessDays(now, -3),
  },
  {
    id: "admin-1",
    email: "admin@tenderhub.gov",
    name: "System Administrator",
    role: "admin",
    organizationName: "TenderHub Platform",
    phone: "+1-555-0301",
    address: "100 Platform Way, Digital City",
    createdAt: addBusinessDays(now, -400),
    updatedAt: addBusinessDays(now, -1),
  },
  {
    id: "admin-2",
    email: "support@tenderhub.gov",
    name: "Platform Support",
    role: "admin",
    organizationName: "TenderHub Platform",
    phone: "+1-555-0302",
    address: "100 Platform Way, Digital City",
    createdAt: addBusinessDays(now, -350),
    updatedAt: addBusinessDays(now, -2),
  },
]

// Mock Audit Events
export const mockAuditEvents = [
  {
    id: "audit-1",
    timestamp: addBusinessDays(now, -1),
    source: "core-canister",
    kind: "tender_created",
    data: "New tender 'Digital Infrastructure Upgrade' created by Ministry of Infrastructure",
    userId: "entity-1",
    userRole: "entity",
  },
  {
    id: "audit-2", 
    timestamp: addBusinessDays(now, -1),
    source: "core-canister",
    kind: "bid_submitted",
    data: "Bid submitted for tender 'School Building Construction' by TechFlow Solutions",
    userId: "provider-1",
    userRole: "provider",
  },
  {
    id: "audit-3",
    timestamp: addBusinessDays(now, -2),
    source: "escrow-adapter",
    kind: "escrow_created",
    data: "Escrow account created for tender 'School Building Construction' - Amount: $27,500,000",
    userId: "system",
    userRole: "system",
  },
  {
    id: "audit-4",
    timestamp: addBusinessDays(now, -2),
    source: "core-canister", 
    kind: "tender_awarded",
    data: "Tender 'School Building Construction' awarded to TechFlow Solutions",
    userId: "entity-1",
    userRole: "entity",
  },
  {
    id: "audit-5",
    timestamp: addBusinessDays(now, -3),
    source: "core-canister",
    kind: "dispute_filed",
    data: "Dispute filed by Elite Construction Co. for tender evaluation discrepancy",
    userId: "provider-2",
    userRole: "provider",
  },
  {
    id: "audit-6",
    timestamp: addBusinessDays(now, -3),
    source: "core-canister",
    kind: "clarification_requested",
    data: "Clarification requested for tender 'Digital Infrastructure Upgrade' by Global Services Ltd.",
    userId: "provider-3",
    userRole: "provider",
  },
  {
    id: "audit-7",
    timestamp: addBusinessDays(now, -4),
    source: "escrow-adapter",
    kind: "payment_released",
    data: "Milestone payment of $2,000,000 released for completed deliverable",
    userId: "admin-1",
    userRole: "admin",
  },
  {
    id: "audit-8",
    timestamp: addBusinessDays(now, -5),
    source: "core-canister",
    kind: "evaluation_completed",
    data: "Evaluation completed for tender 'School Building Construction' - 4 bids evaluated",
    userId: "entity-1",
    userRole: "entity",
  },
  {
    id: "audit-9",
    timestamp: addBusinessDays(now, -6),
    source: "core-canister",
    kind: "user_registered",
    data: "New provider 'Innovation Partners' registered on the platform",
    userId: "admin-1",
    userRole: "admin",
  },
  {
    id: "audit-10",
    timestamp: addBusinessDays(now, -7),
    source: "core-canister",
    kind: "tender_published",
    data: "Tender 'Medical Equipment Procurement' published and opened for bidding",
    userId: "entity-2",
    userRole: "entity",
  },
]
